---
# Organization to pull metrics from
organization: 'ibm'

# Start date to pull metrics from
since: '2026-01-01'

# GitHub Pages path to the repository
# Used for handling relative paths for assets
basePath: '/org-dashboard'
